services:
  redis:
    image: redis:latest
    container_name: redis
    hostname: redis
    volumes:
      - redis_data:/data
    expose:
      - 6379
    ports:
      - 8082:6379
    restart: always
  label_studio:
    image: heartexlabs/label-studio:latest
    # build:
    #   context: label_studio
    #   dockerfile: Dockerfile
    container_name: label_studio
    hostname: labelstudio
    expose:
      - 8080
    ports:
      - 8082:8080
    restart: always
    volumes:
      - label_studio_data:/label-studio/data
    links:
    - redis
  # model_engine:
  #   image: pbouill/model_engine:latest
    # build:
    #   context: model_engine
    #   dockerfile: Dockerfile
    #   args:
    #     - REPO_VER
    #     - REQ_FILE_VER
    # container_name: model_engine
    # hostname: model_engine
    # environment:
    #   - MODEL_DIR=/models
    #   - DATASET_DIR=/datasets
    #   - IMAGE_DIR=/images
    #   - LABEL_STUDIO_MEDIA_DIR=/label_studio_data/media
      # - RQ_QUEUE_NAME=default
      # - REDIS_HOST=redis
      # - REDIS_PORT=6379
      # - LABEL_STUDIO_USE_REDIS=true
      # - LABEL_STUDIO_SERVER=http://labelstudio:8080
    # expose:
    #   - 9090
    # ports:
    #   - 8888:9090
    # # links:
    # #   - redis
    # # depends_on:
    # #   - redis
    # restart: always
    # volumes:
    #   - model_engine_models:/models
    #   - model_engine_datasets:/datasets
    #   - model_engine_images:/images
    #   - label_studio_data:/label_studio_data:ro
volumes:
  label_studio_data:
  redis_data:
    external: True
  model_engine_data:
    external: True
  # model_engine_datasets:
  # model_engine_images:
