services:
  redis:
    image: redis
    container_name: redis
    hostname: redis
    volumes:
      - redis_data:/data
    expose:
      - 6379
    ports:
      - 6379:6379
    restart: always
  label_studio:
    build:
      context: label_studio
      dockerfile: Dockerfile
    container_name: label_studio
    hostname: labelstudio
    expose:
      - 8080
    ports:
      - 8080:8080
    restart: always
    volumes:
      - label_studio_data:/label-studio/data
  model_engine:
    build:
      context: model_engine
      dockerfile: Dockerfile
    container_name: model_engine
    hostname: model_engine
    environment:
      - MODEL_DIR=/models
      - DATASET_DIR=/datasets
      - IMAGE_DIR=/images
      - RQ_QUEUE_NAME=default
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - LABEL_STUDIO_USE_REDIS=true
      - LABEL_STUDIO_SERVER=http://cacplcemudev:8080
    ports:
      - 8888:9090
    depends_on:
      - redis
    restart: always
    volumes:
      - model_engine_models:/models
      - model_engine_datasets:/datasets
      - model_engine_images:/images
volumes:
  label_studio_data:
  redis_data:
  model_engine_models:
  model_engine_datasets:
  model_engine_images:
