services:
  redis:
    image: redis
    container_name: redis
    hostname: redis
    volumes:
      - redis_data:/data
    expose:
      - 6379
    restart: always
  label_studio:
    build:
      context: label_studio
      dockerfile: Dockerfile
    container_name: label_studio
    hostname: labelstudio
    ports:
      - 8080:8080
    restart: always
    volumes:
      - label_studio_data:/label-studio/data
  model_engine:
    build:
      context: model_engine
      dockerfile: Dockerfile
    container_name: model_engine
    hostname: model_engine
    ports:
      - 9090:9090
    restart: always
    volumes:
      - model_engine_data:/models
volumes:
  label_studio_data:
  redis_data:
  model_engine_data:
